
name: TFDemo3AKS

trigger:
- main  # Adjust this based on your branch configuration

pr:
- main
  
pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployInfrastructure
  displayName: 'Deploy Infrastructure'
  steps:
  - checkout: self
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: AzureCLI@2
    displayName: Fetch credentials for azure
    inputs:
      azureSubscription: 'sc-azure-sp' 
      scriptType: bash
      addSpnToEnvironment: true
      useGlobalConfig: true
      scriptLocation: inlineScript
      inlineScript: |
        echo "##vso[task.setvariable variable=ARM_TENANT_ID;]$tenantId"
        echo "##vso[task.setvariable variable=ARM_CLIENT_ID;]$servicePrincipalId"
        echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;]$servicePrincipalId"
        echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;]$servicePrincipalKey"
        echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;]$(az account show --query id -o tsv)"
        az storage account create --name rktfstatesa2024 --resource-group RG-TF-DEMO --location eastus --sku Standard_LRS
        az storage container create --name terraform --account-name rktfstatesa2024

  - task: TerraformTaskV4@4
    displayName: Terraform Init

    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/demo3'
      backendServiceArm: 'sc-azure-sp' #this works with service principal connection only
      backendAzureRmResourceGroupName: 'RG-TF-DEMO'
      backendAzureRmStorageAccountName: 'rktfstatesa2024'
      backendAzureRmContainerName: 'terraform'
      backendAzureRmKey: 'dev.tfstate'

  - task: TerraformTaskV4@4
    displayName: Terraform Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      commandOptions: '-var-file="dev.tfvars"'
      workingDirectory: '$(System.DefaultWorkingDirectory)/demo3'
      environmentServiceNameAzureRM: 'sc-azure-sp'

  - task: TerraformTaskV4@4
    displayName: Terraform Apply
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)/demo3'
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-var-file="dev.tfvars" -auto-approve'
      environmentServiceNameAzureRM: 'sc-azure-sp'
      
